version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: study_planner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: fastapi_app
    environment:
      DATABASE_URL: postgresql://user:password@db/study_planner
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
